# Generated by Django 3.2.8 on 2022-01-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='numero_oficio',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
