# Generated by Django 3.2.8 on 2022-01-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_movimentacao_numero_oficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
