# Generated by Django 3.2.8 on 2021-12-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_alter_telefone_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RG'),
        ),
    ]
