# Generated by Django 3.2.8 on 2021-11-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doacaoevento',
            unique_together={('pessoa', 'evento')},
        ),
    ]
