# Generated by Django 3.2.8 on 2022-01-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacaoevento',
            options={'ordering': ['recebido'], 'verbose_name': 'Doação de Evento', 'verbose_name_plural': 'Doações de Eventos'},
        ),
    ]
